backend/app/urls.py
from django.urls import include, path

import hr.urls

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include(hr.urls)),
]

backend/hr/urls.py
from django.urls import path

from . import views

app_name = "hr"


urlpatterns = [
    path("", views.index, name="index"),
    path("reset_db", views.reset_db, name="reset_db"),
    path("add_employee", views.add_employee, name="add_employee"),
    path("employees", views.employees, name="employees"),
    path("employee/<id>/address", views.address, name="address"),
    path("employee/<id>/basic_info", views.basic_info, name="basic_info"),
    path("employee/<id>/contract", views.contract, name="contract"),
    path("employee/<id>", views.employee, name="employee"),
    path("employee/delete/<id>", views.delete_employee, name="delete_employee"),
    path("employee/<id>/promote", views.promote, name="promote"),
    path("employee/<id>/add_to_team", views.add_to_team, name="add_to_team"),
    path("teams", views.teams, name="teams"),
    path("add_team", views.add_team, name="add_team"),
    path("team/<id>", views.team, name="team"),
    path("team/delete/<id>", views.delete_team, name="delete_team"),
    path("team/<id>/members", views.members, name="members"),
]

backend/hr/models.py
from django.db import models


class BasicInfo(models.Model):
    name = models.CharField(null=False, max_length=100)
    email = models.EmailField(null=False)

    def __str__(self):
        return f"{self.name} <{self.email}>"


class Address(models.Model):
    address_line1 = models.CharField(null=False, max_length=100)
    address_line2 = models.CharField(null=True, blank=True, max_length=100)
    city = models.CharField(null=False, max_length=100)
    zip_code = models.IntegerField(null=False)

    def __str__(self):
        return f"Adress #{self.pk}"


class Contract(models.Model):
    hiring_date = models.DateField(null=False, max_length=30)
    job_title = models.CharField(null=False, max_length=100)

    def __str__(self):
        return f"{self.job_title} - hired on {self.hiring_date}"


class Team(models.Model):
    name = models.CharField(null=False, max_length=100)

    def __str__(self):
        return f"{self.name} team"


class Employee(models.Model):
    basic_info = models.OneToOneField(BasicInfo, null=False, on_delete=models.CASCADE)
    contract = models.OneToOneField(Contract, null=False, on_delete=models.CASCADE)
    address = models.OneToOneField(Address, null=False, on_delete=models.CASCADE)
    manager = models.ForeignKey("self", on_delete=models.SET_NULL, null=True)
    is_manager = models.BooleanField(default=False)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)

    def __str__(self):
        res = self.basic_info.name
        if self.is_manager:
            res += " (manager)"
        return res

backend/hr/forms.py
from django import forms

from .models import Address, BasicInfo, Contract, Team


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["address_line1", "address_line2", "city", "zip_code"]
        labels = {
            "address_line1": "",
            "address_line2": "",
        }


class BasicInfoForm(forms.ModelForm):
    class Meta:
        model = BasicInfo
        fields = ["name", "email"]


class NewContractForm(forms.ModelForm):
    class Meta:
        date_widget = forms.DateInput()
        date_widget.input_type = "date"
        model = Contract
        fields = ["hiring_date", "job_title"]
        widgets = {"hiring_date": date_widget}


class UpdateContractForm(forms.ModelForm):
    class Meta:
        date_widget = forms.DateInput(attrs={"readonly": True})
        date_widget.input_type = "date"
        model = Contract
        fields = ["hiring_date", "job_title"]
        widgets = {"hiring_date": date_widget}


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ["name"]

    def clean(self):
        super().clean()
        name = self.cleaned_data["name"]
        with_same_name = Team.objects.filter(name=name)
        if with_same_name:
            self.add_error("name", "a team with the same name already exists")


class AddToTeamForm(forms.Form):
    team = forms.ModelChoiceField(queryset=Team.objects)

backend/hr/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import (
    AddressForm,
    AddToTeamForm,
    BasicInfoForm,
    NewContractForm,
    TeamForm,
    UpdateContractForm,
)
from .models import Address, BasicInfo, Contract, Employee, Team


def index(request):
    return render(request, "hr/index.html")


def reset_db(request):
    if request.method == "GET":
        return render(request, "hr/reset_db.html")
    else:
        BasicInfo.objects.all().delete()
        Contract.objects.all().delete()
        Address.objects.all().delete()
        Employee.objects.all().delete()
        Team.objects.all().delete()
        return redirect("hr:index")


def employees(request):
    return render(
        request,
        "hr/employees.html",
        context={"employees": Employee.objects.all()},
    )


def employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    return render(request, "hr/employee.html", context=context)


def delete_employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    if request.method == "GET":
        context = {"employee": employee}
        return render(request, "hr/delete_employee.html", context=context)
    else:
        employee.delete()
        return redirect("hr:employees")


def add_employee(request):
    status = 200
    if request.method == "GET":
        address_form = AddressForm()
        basic_info_form = BasicInfoForm()
        contract_form = NewContractForm()
    else:
        address_form = AddressForm(request.POST)
        basic_info_form = BasicInfoForm(request.POST)
        contract_form = NewContractForm(request.POST)
        if (
            address_form.is_valid()
            and basic_info_form.is_valid()
            and contract_form.is_valid()
        ):
            address = address_form.save()
            basic_info = basic_info_form.save()
            contract = contract_form.save()
            Employee.objects.create(
                address=address, basic_info=basic_info, contract=contract
            )
            return redirect("hr:employees")
        else:
            status = 400
    return render(
        request,
        "hr/add_employee.html",
        {
            "address_form": address_form,
            "basic_info_form": basic_info_form,
            "contract_form": contract_form,
        },
        status=status
    )


def address(request, id):
    status = 200
    employee = get_object_or_404(Employee, pk=id)
    address = employee.address
    old_line2 = address.address_line1
    if request.method == "GET":
        form = AddressForm(instance=address)
    else:
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            # BUG
            address.address_line2 = old_line2
            address.save()
            return redirect("hr:employee", id=id)
        else:
            status = 400
    return render(request, "hr/address.html", {"form": form, "employee": employee}, status=status)


def basic_info(request, id):
    status = 200
    employee = get_object_or_404(Employee, pk=id)
    basic_info = employee.basic_info
    if request.method == "GET":
        form = BasicInfoForm(instance=basic_info)
    else:
        form = BasicInfoForm(request.POST, instance=basic_info)
        if form.is_valid():
            form.save()
            return redirect("hr:employee", id=id)
        else:
            status = 400
    return render(request, "hr/basic_info.html", {"form": form, "employee": employee}, status=status)


def contract(request, id):
    status = 200
    employee = get_object_or_404(Employee, pk=id)
    contract = employee.contract
    if request.method == "GET":
        form = UpdateContractForm(instance=contract)
    else:
        form = UpdateContractForm(request.POST, instance=contract)
        if form.is_valid():
            form.save()
            return redirect("hr:employee", id=id)
        else:
            status = 400
    return render(request, "hr/contract.html", {"form": form, "employee": employee}, status=status)


def promote(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    if request.method == "POST":
        employee.is_manager = True
        employee.save()
        return redirect("hr:employees")
    else:
        return render(request, "hr/promote.html", context=context)


def teams(request):
    return render(
        request,
        "hr/teams.html",
        context={"teams": Team.objects.all()},
    )


def add_team(request):
    status = 200
    if request.method == "GET":
        form = TeamForm()
    else:
        form = TeamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("hr:teams")
        else:
            status = 400

    return render(request, "hr/add_team.html", {"form": form}, status=status)


def team(request, id):
    team = get_object_or_404(Team, pk=id)
    return render(
        request,
        "hr/team.html",
        context={"team": team},
    )


def members(request, id):
    team = get_object_or_404(Team, pk=id)
    members = Employee.objects.filter(team=team)
    return render(
        request,
        "hr/members.html",
        context={"team": team, "members": members},
    )


def delete_team(request, id):
    team = get_object_or_404(Team, pk=id)
    if request.method == "GET":
        return render(
            request,
            "hr/delete_team.html",
            context={"team": team},
        )
    else:
        team.delete()
        return redirect("hr:teams")


def add_to_team(request, id):
    status = 200
    employee = get_object_or_404(Employee, pk=id)
    if request.method == "GET":
        form = AddToTeamForm()
    else:
        form = AddToTeamForm(request.POST)
        if form.is_valid():
            employee.team = form.cleaned_data["team"]
            employee.save()
            return redirect("hr:employee", id=id)
        else:
            status = 400
    return render(
        request,
        "hr/add_to_team.html",
        {
            "employee": employee,
            "form": form,
        },
        status=status
    )

backend/hr/templates/hr/add_employee.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Add Employee

{% endblock %}
{% block content %}
  <h2>Add new employee</h2>

  <form method='post' action='{% url 'hr:add_employee' %}' class='form'>
    <fieldset>
      <legend>Basic Info</legend>
      {% bootstrap_form basic_info_form %}
    </fieldset>
    <fieldset>
      <legend>Address</legend>
      {% bootstrap_form address_form %}
    </fieldset>
    <fieldset>
      <legend>Contract</legend>
      {% bootstrap_form contract_form %}
      {% bootstrap_button button_type="submit" content="Add" %}
    </fieldset>
  </form>
{% endblock %}

backend/hr/templates/hr/add_team.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Add Team

{% endblock %}
{% block content %}
  <h2>Create new team</h2>

  <form action='{% url "hr:add_team" %}' method='post' class='form'>
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add" %}
  </form>
{% endblock %}

backend/hr/templates/hr/add_to_team.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Add to eam

{% endblock %}
{% block content %}

  <h2>Add new member to existing team</h2>

  Name: {{ employee.basic_info.name }}
  <form method='post' action='{% url 'hr:add_to_team' employee.id %}' class='form'>
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add" %}
  </form>
{% endblock %}

backend/hr/templates/hr/address.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Edit Address

{% endblock %}
{% block content %}
  <h2>Edit Addres</h2>

  Editing address of {{ employee.basic_info.name }}

  <form action='{% url 'hr:address'  employee.id %}' method='post' class='form'>
   {% bootstrap_form form %}
   {% bootstrap_button type="submit" content="Update" %}
  </form>
{% endblock %}

backend/hr/templates/hr/base.html
{% load static %}
{% load django_browser_reload %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html>
  <head>
    <title>HR DB -      {% block title %}
      {% endblock %}
</title>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel='shortcut icon' href='{% static "favicon.ico" %}'>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel='stylesheet' href='{% static "style.css" %}'>
  </head>
  <body>

    <nav>
      <a href='/'>Home</a>

    </nav>
    {% block content %}

    {% endblock %}

    <footer>
      Version 1.0.9

    </footer>
   {% django_browser_reload_script %}
  </body>
</html>

backend/hr/templates/hr/basic_info.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}

{% block title %}
  Edit basic Information

{% endblock %}
{% block content %}

  <h2>Edit Employee Basic Information</h2>

  <form action='{% url 'hr:basic_info' employee.id %}' method='post' class='form'>
    {% bootstrap_form form %}
    {% bootstrap_button type="submit" content="Update" %}
  </form>
{% endblock %}

backend/hr/templates/hr/contract.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Edit Legal Information

{% endblock %}
{% block content %}

  <h2>Edit Employee Legal Information</h2>

  <form action='{% url 'hr:contract' employee.id %}' method='post'>
    {% bootstrap_form form %}
    {% bootstrap_button type="submit" content="Update" %}
  </form>
{% endblock %}

backend/hr/templates/hr/delete_employee.html
{% extends 'hr/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
  Delete Employee

{% endblock %}
{% block content %}
  <h2>Delete Employee</h2>

  <p>
    You are about to delete records about
    <br>
    name: {{ employee.basic_info.name }}
    <br>
    email: {{ employee.basic_info.email }}
    <br>

  </p>
  <p>
    This cannot be undone

  </p>
  <form method='post' action='{% url 'hr:delete_employee' employee.id %}'>
     {% csrf_token %}
     <button type='submit' class='btn btn-danger'>Proceed</button>
  </form>
{% endblock %}

backend/hr/templates/hr/delete_team.html
{% extends 'hr/base.html' %}

{% block title %}
  Delete Team

{% endblock %}
{% block content %}
  <h2>Delete Team</h2>
  <p>
    You are about to delete the team "{{ team.name }}"
  </p>
  <p></p>
  This cannot be undone

  <form method='post' action='{% url 'hr:delete_team' team.id %}'>
   {% csrf_token %}
   <button type='submit' class='btn btn-danger'>Proceed</button>

  </form>
{% endblock %}

backend/hr/templates/hr/employee.html
{% extends 'hr/base.html' %}
{% block title %}
  Edit Employee

{% endblock %}
{% block content %}
  <h2>Edit Employee</h2>
  <p>
    {{ employee.basic_info.name }} - {{ employee.basic_info.email }}
  </p>
  <p>
    {{ employee.contract.job_title }}
  </p>
  <p>
    Hired on {{ employee.contract.hiring_date }}
  </p>
  <ul>
    <li>
      <a href='{% url 'hr:basic_info' employee.id %}'>Update basic info</a>
    </li>
    <li>
      <a href='{% url 'hr:address' employee.id %}'>Update address</a>
    </li>
    <li>
      <a href='{% url 'hr:contract' employee.id %}'>Update contract</a>
    </li>
    <li>
      <a href='{% url 'hr:promote' employee.id %}'>Promote as manager</a>
    </li>
    <li>
      <a href='{% url 'hr:add_to_team' employee.id %}'>Add to team</a>
    </li>
  </ul>
{% endblock %}

backend/hr/templates/hr/employees.html
{% extends 'hr/base.html' %}
{% block title %}
  Employees
{% endblock %}
{% block content %}

  {% if employees %}
    <h2>Employees ({{ employees| length }})</h2>
    <table class='table'>
      <thead>
        <tr>
          <th>name</th>
          <th>email</th>
          <th>manager?</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
          <tr>
            <td>{{ employee.basic_info.name }}</td>
            <td>{{ employee.basic_info.email }}</td>
            <td>
              {% if employee.is_manager %}
                <strong>yes</strong>
              {% else %}
                no
              {% endif %}
            </td>
            <td>
              <a href='{% url 'hr:employee' employee.id %}' class='btn btn-primary'>Edit</a>
            </td>
            <td>
              <a href='{% url 'hr:delete_employee' employee.id %}' class='btn btn-primary'>Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <h2>Employees</h2>

      No employees yet.

  {% endif %}
{% endblock %}

backend/hr/templates/hr/index.html
{% extends 'hr/base.html' %}

{% block title %}
  Home

{% endblock %}
{% block content %}

  <h1 id='title'>
    HR DB - Home

  </h1>
  <h2>
    Employees
  </h2>
  <ul>
    <li>
      <a href='{% url 'hr:employees' %}'>List employees</a>
     <li>
      <a href='{% url 'hr:add_employee' %}'>Add new employee</a>

     </li>
    </li>
  </ul>
  <h2>Teams</h2>

  <ul>
    <li>
      <a href='{% url 'hr:teams' %}'>List teams</a>
    </li>
    <li>
      <a href='{% url 'hr:add_team' %}'>Create new team</a>
    </li>
  </ul>
  <h2>Danger zone</h2>

  <ul>
    <li>
     <a href='{% url 'hr:reset_db' %}'>Reset database</a>
    </li>
  </ul>
{% endblock %}

backend/hr/templates/hr/promote.html
{% extends 'hr/base.html' %}

{% block title %}
  Promote Employee

{% endblock %}
{% block content %}

  <h2>Promote employee</h2>
  <p>
    {{ employee.basic_info.name }} is going to be promoted as a manager
  </p>
  <form action='{% url 'hr:promote' employee.id %}' method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-primary'>Proceed</button>

  </form>
{% endblock %}

backend/hr/templates/hr/reset_db.html
{% extends 'hr/base.html' %}
{% block title %}
  Reset database

{% endblock %}
{% block content %}
  <h2>Reset Database</h2>

  <p>
    You are about to delete all the information from the database.

  </p>
  <p>
   This cannot be undone

  </p>
  <form method='post' action='{% url 'hr:reset_db' %}'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger'>Proceed</button>
  </form>
{% endblock %}